from slack_bolt.async_app import AsyncApp
from .feedback_buttons import handle_feedback_button
from agent.state import get_pending_brief, clear_pending_brief

def register(app: AsyncApp):
    app.action("feedback")(handle_feedback_button)
    app.action("open_briefagent")(handle_open_briefagent)
    app.action("post_brief_to_channel")(handle_post_brief_to_channel)

async def handle_open_briefagent(ack, body, logger):
    await ack()
    logger.info("BriefAgent button clicked")

# Called by: Slack when the user clicks the "Post to channel →" button in the assistant sidebar
# grabs the saved brief from state, posts it as a formatted Block Kit message to the original 
# channel the user typed /brief in, then clears the state
async def handle_post_brief_to_channel(ack, body, client, logger):
    await ack()
    try:
        user_id = body["user"]["id"]
        origin_channel = body["actions"][0]["value"]

        pending = get_pending_brief(user_id)

        if not pending or pending["brief"] is None:
            logger.warning("Post to channel clicked but no brief found")
            return

        brief = pending["brief"]

        # Split brief into 2900 char chunks
        chunks = [brief[i:i+2900] for i in range(0, len(brief), 2900)]

        blocks = []
        for chunk in chunks:
            blocks.append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": chunk}
            })

        blocks.append({
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"📊 Brief generated by BriefAgent for <@{user_id}>"
                }
            ]
        })

        await client.chat_postMessage(
            channel=origin_channel,
            text=brief[:150],
            blocks=blocks
        )

        clear_pending_brief(user_id)
        logger.info(f"Brief posted to channel {origin_channel}")

    except Exception as e:
        logger.exception(f"Failed to post brief to channel: {e}")