"""PDF export helpers for turning a generated brief into a downloadable file."""

import io
import re
from datetime import date
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT


def _clean(text):
    """Normalize the brief’s Markdown into PDF-safe rich text fragments."""
    # Convert strong emphasis to ReportLab HTML-style tags.
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    # Remove single-asterisk emphasis while keeping the inner text visible.
    text = re.sub(r'(?<!\*)\*(?!\*)(.*?)(?<!\*)\*(?!\*)', r'\1', text)
    # Render inline code as italic text to keep the layout readable.
    text = re.sub(r'`(.*?)`', r'<i>\1</i>', text)
    text = text.replace('&', '&amp;')
    return text


def generate_pdf(topic: str, brief: str) -> bytes:
    """Build a stylized PDF document from the generated research brief."""
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.9 * inch,
        leftMargin=0.9 * inch,
        topMargin=1.0 * inch,
        bottomMargin=1.0 * inch
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "BriefTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=colors.HexColor("#1a1a1a"),
        spaceAfter=4
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#888888"),
        spaceAfter=16,
        alignment=TA_CENTER
    )
    heading_style = ParagraphStyle(
        "BriefHeading",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=colors.HexColor("#1a1a1a"),
        spaceBefore=16,
        spaceAfter=6,
        borderPad=0
    )
    body_style = ParagraphStyle(
        "BriefBody",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#333333"),
        leading=15,
        spaceAfter=6
    )
    bullet_style = ParagraphStyle(
        "BriefBullet",
        parent=body_style,
        leftIndent=16,
        spaceAfter=4
    )

    story = []

    # The PDF title and metadata establish the document context at the top.
    story.append(Paragraph(f"Research Brief: {topic}", title_style))
    story.append(Paragraph(
        f"Generated by BriefAgent \u00b7 {date.today().strftime('%B %d, %Y')}",
        meta_style
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e0e0e0")))
    story.append(Spacer(1, 12))

    # Convert the assistant’s text output into a report structure line by line.
    for line in brief.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 4))
            continue

        # Section headers: ## Header or *HEADER*
        if line.startswith("## ") or line.startswith("# "):
            text = line.lstrip("#").strip()
            story.append(Paragraph(text, heading_style))

        # Bullet points
        elif line.startswith("- ") or line.startswith("• "):
            text = _clean(line[2:])
            story.append(Paragraph(f"• &nbsp; {text}", bullet_style))

        # Horizontal rule
        elif line.startswith("---"):
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e0e0e0")))
            story.append(Spacer(1, 4))

        # Normal paragraph
        else:
            text = _clean(line)
            story.append(Paragraph(text, body_style))

    doc.build(story)
    return buffer.getvalue()


async def upload_brief_as_pdf(client, channel_id, topic, brief, logger):
    try:
        pdf_bytes = generate_pdf(topic, brief)
        safe_topic = topic[:40].replace("/", "-").replace("\\", "-")

        response = await client.files_upload_v2(
            channel=channel_id,
            content=pdf_bytes,
            filename=f"Brief - {safe_topic}.pdf",
            title=f"Brief: {topic}",
        )
        logger.info(f"PDF brief uploaded to {channel_id}")
        return response.get("file", {}).get("permalink")
    except Exception as e:
        logger.exception(f"PDF upload failed: {e}")
        return None