"""Plain-text export helpers for the generated research brief."""

from datetime import date


def generate_txt(topic: str, brief: str) -> str:
    """Convert a Slack-formatted brief into a clean text document."""
    header = (
        f"RESEARCH BRIEF: {topic.upper()}\n"
        f"Generated by BriefAgent | {date.today().strftime('%B %d, %Y')}\n"
        f"{'='*60}\n\n"
    )
    # Strip Slack mrkdwn markers before exporting the plain-text version.
    import re
    clean = re.sub(r'\*\*(.*?)\*\*', r'\1', brief)
    clean = re.sub(r'\*(.*?)\*', r'\1', clean)
    clean = re.sub(r'`(.*?)`', r'\1', clean)
    return header + clean


async def upload_brief_as_txt(client, channel_id, topic, brief, logger):
    try:
        txt_content = generate_txt(topic, brief)
        safe_topic = topic[:40].replace("/", "-").replace("\\", "-")

        response = await client.files_upload_v2(
            channel=channel_id,
            content=txt_content,
            filename=f"Brief - {safe_topic}.txt",
            title=f"Brief: {topic}",
        )
        logger.info(f"TXT brief uploaded to {channel_id}")
        return response.get("file", {}).get("permalink")
    except Exception as e:
        logger.exception(f"TXT upload failed: {e}")
        return None